[package]
name = "neighbo-rs"
version = "0.1.0"
authors = ["Noah Wahl <noah.ares@yahoo.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.70", features = ["backtrace"] }
assert_float_eq = "1"
bitvec = "1.0.1"
clap = { version = "4.2.4", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
counter = "0.5.7"
csv = "1.2.2"
env_logger = "0.10.0"
exitcode = "1.1.2"
itertools = { version = "0.10.5", features = ['use_alloc'] }
log = "0.4.17"
logging_timer = "1.1.0"
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
ordered-float = "3.7.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rand_xoshiro = "0.6.0"
rayon = "1.7.0"
regex = "1.9.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

[profile.ultra]
inherits = "release"
codegen-units = 1
lto = true
panic = "abort"

[profile.perf]
inherits = "ultra"
debug = 1

[profile.relwithdeb]
inherits = "release"
debug = 1

[[bin]]
name = "metrics"
path = "src/bin/metrics/main.rs"
